### ISSUE TITLE
Need help with MES files of Fortissimo FA

### ISSUE THREAD

**Issue by LucasHood1234** [crskycode/CIRCUS_Script_Tool#1]
Hello, currently i am working to get datas of the game Fortissimo FA in order to make a patch, i have got the scripts for gameplay's story but still unable to get the files for Glossary, scene names and music library, as well as other MES files, can you check on this? Much appreciated.

**Comment by crskycode** [comment]
Use this tool https://github.com/crskycode/CIRCUS_MES_FA
